language: nix
sudo: false
env:
  - nix-build -A test-O3
  - nix-build -A test-O2
  - nix-build -A test-O1
  - nix-build -A test-nojit
  - nix-build -A check-generated-code --arg check true
script:
  - $test
